### ISSUE TITLE
Push notifications in iOS

### ISSUE THREAD

**Issue by ltaljaard** [xamarin/Sport#1]
It seems push notifications are not working in iOS. I've noticed that in the Android project, App.CurrentAthlete.DeviceToken is set to a value in PushNotifications.cs class PushHandlerService method OnRegistered. But in the iOS project there is no equivalent and so I think that App.CurrentAthlete.DeviceToken stays uninitialized on iOS and therefore all the push notification code gets bypassed. Could you please confirm how to initialize App.CurrentAthlete.DeviceToken in iOS and/or update this solution?

**Comment by ltaljaard** [comment]
Never mind, it seems remote notifications are not supported in the iOS simulator.

**Comment by rob-derosa** [comment]
Push notifications are also disabled in the public demo. You can spin up your own AMS backend to enable them if you would like to test.
