### ISSUE TITLE
Webpage not available, how to fix on this issue ? 

### ISSUE THREAD

**Issue by uthens** [xamarin/Sport#10]
I found the problem when i run on Sport.Andriod project.

This is information show on simulator:
I tested on login on the first screen.
The webpage at: https://c9389503-0ee0-42310b9ee.azurewebsite.net/loin/google could not be loaded because: 

net::ERR_NAME_NOT_RESOLVED

Do you have any suggestion on this ?

**Comment by uthens** [comment]
any update on this ? :) i still wait feedback from your team.

**Comment by rob-derosa** [comment]
I was unable to reproduce the issue you are experiencing.
