### ISSUE TITLE
Native Authentication

### ISSUE THREAD

**Issue by vishalvatsal** [xamarin/Sport#13]
Hi Team, 

Not sure if this is the right place to bring this up. Is there a reason you do not have any samples that would use Native authentication? 

I am new to Xamarin. And I do think that if I have an android phone, majority of time a user will have a google account, why would you want user to enter credentials again? 

Can you not just use existing identity already on the phone? If so can you at-least have a sample or implement it in your samples?  

Thank you

**Comment by rob-derosa** [comment]
This specific sample is about sharing common code across multiple OS. iOS does not support a "system Google account" that other apps can use for authentication.

**Comment by Amplicade** [comment]
Was there any specific reason to not use Xamarin.Auth but rather have a kind of custom implementation for Google Login? Do you expect any issues replacing it with Xamarin.Auth and using also Facebook, Twitter, etc.?

**Comment by rob-derosa** [comment]
In order to secure the Azure backend against unauthenticated calls, I had to use the Azure-sanctioned APIs to authenticate in order to generate an Azure auth token.

**Comment by Amplicade** [comment]
Ok I see, so using OAuth would not be saving our backend. Following this idea, I tried to add Facebook, on the backend as well as on the App (I followed the Azure docs [here](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#how-to-work-with-authentication) and [here](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/#overview)). 

My Backend now has following new route:
```[Route("api/getUserIdentityFacebook")]
        public async Task<FacebookCredentials> GetUserIdentityFacebook()
        {
            ServiceUser serviceUser = User as ServiceUser;
            if (serviceUser != null)
            {
                var identity = await serviceUser.GetIdentitiesAsync();
                var credentials = identity.OfType<FacebookCredentials>().FirstOrDefault();
                return credentials;
            }
            return null;
        }```

and my App has the following calls:

1. DisplayWebView() in Authentication.cs on iOS/Android:
``return await AzureService.Instance.Client.LoginAsync(Forms.Context, MobileServiceAuthenticationProvider.Facebook);``

2. ShowGoogleAuthenticationView() in AuthenticationViewModel.cs
``var identity = await AzureService.Instance.Client.InvokeApiAsync("getUserIdentityFacebook", null, HttpMethod.Get, null);``

Starting the App it is trying to load the Facebook Login Page, but it is showing an error "Not Logged In: You are not logged in. Please login and try again." 

I don't know if I'm missing anything here. I tried a lot getting this running with Facebook but I'm stuck right now. I got this working with Twitter. 

Any help is highly appreciated! Thank you a lot in advance.

**Comment by rob-derosa** [comment]
I'm no Azure expert so I unfortunately cannot advise. I'd hit up the Azue forums or give StackOverflow a try.




On Mon, Jul 11, 2016 at 3:09 PM -0700, "Amplicade" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I see, so using OAuth would not be saving our backend. Following this idea, I tried to add Facebook, on the backend as well as on the App (I followed the Azure docs here<https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/#how-to-work-with-authentication> and here<https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/#overview>).

My Backend now has following new route:

        public async Task<FacebookCredentials> GetUserIdentityFacebook()
        {
            ServiceUser serviceUser = User as ServiceUser;
            if (serviceUser != null)
            {
                var identity = await serviceUser.GetIdentitiesAsync();
                var credentials = identity.OfType<FacebookCredentials>().FirstOrDefault();
                return credentials;
            }
            return null;
        }```

and my App has the following calls:

1. DisplayWebView() in Authentication.cs on iOS/Android:
``return await AzureService.Instance.Client.LoginAsync(Forms.Context, MobileServiceAuthenticationProvider.Facebook);``

2. ShowGoogleAuthenticationView() in AuthenticationViewModel.cs
``var identity = await AzureService.Instance.Client.InvokeApiAsync("getUserIdentityFacebook", null, HttpMethod.Get, null);``

Starting the App it is trying to load the Facebook Login Page, but it is showing an error "Not Logged In: You are not logged in. Please login and try again."

I don't know if I'm missing anything here. I tried a lot getting this running with Facebook but I'm stuck right now. I got this working with Twitter.

Any help is highly appreciated! Thank you a lot in advance.


-

**Comment by Amplicade** [comment]
I've found wrong setting in Facebook and it works now. App supports FB, Twitter & Google now. I'm happy to share my code if you are interested. Maybe its worth considering it for the upcoming version.

**Comment by shainefisher** [comment]
I would be interested in seeing this code, if you are still willing to share it? Thanks
