### ISSUE TITLE
authenticate 401 error: deleted_client

### ISSUE THREAD

**Issue by carlosalbertosousa** [xamarin/Sport#16]
I need help for deploy backend service, someone can give me a hand?

**Google**
https://console.developers.google.com

API MANAGER
1-Create new project 
2- Select Credentials and create:  
OAuth client ID
Application type: Web Application
Authorized JavaScript origins: https://testsport.azurewebsites.net
Authorized redirect URIs: https://testsport.net/.auth/login/google

For use with requests from

**Portal Azure**
1-Create: Web+Mobile -> Mobile APP

After select Mobile App, Features Authentication / Authorization
App Service Authentication: On
Action to take when request is not authenticated: Log in with Google
Google -> configure
paste Client Id & Client Secret

In my table:
Authenticate 401 that's an error
Errpr: deleted_client
the OAuth client was deleted

**Comment by rob-derosa** [comment]
We've moved to the new Azure App Services. Latest pushed code should work now.
