### ISSUE TITLE
Expired API key

### ISSUE THREAD

**Issue by SamuelDebruyn** [xamarin/Sport#17]
The latest version available in the app stores uses an expired API key for Google authentication.

**Comment by jobforpetersun** [comment]
I have the same problem.  The app was working previously.  Can the API key be fixed?

**Comment by pstech2020** [comment]
I have the same problem.  The app was previously working for me.

Can the API key be fixed?

**Comment by rob-derosa** [comment]
I will be publishing a new app in the app store soon. For now, you can pull the source and build locally to check out the app.

Thanks!

**Comment by samcov** [comment]
I'm amazed you guys ever compiled the app. I've NEVER found a single Xamarin app that compiled... not a one! Using a freshly installed VS 2015 Enterprise with Xamarin supposedly updated, errors all over the place.

Please install package: 'Xamarin.Android.Support.Vector.Drawable' available in SDK installer.

Xamarin\Xamarin.Android.Support.Vector.Drawable\23.3.0.0\content\./ doesn't exist.	Sport.Mobile.Droid

Seriously?

**Comment by rob-derosa** [comment]
Sorry to hear you're running into build issues. I just pushed an update that I've been working on for awhile that makes it so anyone can challenge anyone (not just the player 1 slot above you).

I ensured that it builds in both VS2015 and Xamarin Studio (stable channel). A few notes on building:

- sometimes if I build each project individually, starting with the PCL, that helps avoid build errors
- in VS, I was getting an odd build error where it wasn't able to reference the Sport.Mobile.Shared PCL for some reason. I removed the reference and re-added it and it built fine.

If you're still hitting issues, I'll do my best to assist.

Cheers,
Rob

**Comment by SiyuYang** [comment]
Hello, I'm able to build the project but got an error (Error: deleted_client The OAuth client was deleted) as I try to log-in. Is this the problem referred to above? How can I try this app?

**Comment by rob-derosa** [comment]
The current source code should not have an expired API key for Google.

**Comment by rob-derosa** [comment]
Hi all, I pushed a bunch of changes recently. If anyone has any issues w/ expired Google API keys or build issue, a small ask to open a new bug so I can track it independently.

Thanks!
