### ISSUE TITLE
iOS Build error while Use VS2015 with macOS build host

### ISSUE THREAD

**Issue by KhuongNtrd** [xamarin/Sport#18]
1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking error: warning: directory not found for option '-F./MobileCenterFrameworks'
1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking error: framework not found CrashReporter
1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): warning : References to 'sqlite3' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): warning : References to 'sqlite3' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed. Please review the build log.

**Comment by rob-derosa** [comment]
This seems to be a build issue w/ Visual Studio when consuming the new Mobile Center SDKs on Windows. Investigating...

**Comment by rob-derosa** [comment]
This should be patched now. If you get build errors, please remove all bin & obj folders and then build the PCL project first.
