### ISSUE TITLE
How to build notes

### ISSUE THREAD

**Issue by itsaboutcode** [xamarin/Sport#20]
Just wondering if there is any tutorial/notes/wiki on how to build this project?

**Comment by ahadk** [comment]
What problem you had on build ? or you asking how to build and use this sample application ?

**Comment by renattomachado** [comment]
How to configure the Setting Constants?

const string _googleUserId = "googleUserId";
		const string _athleteId = "athleteId";
		const string _deviceToken = "deviceToken";
		const string _googleRefreshToken = "googleRefreshToken";
		const string _googleAccessToken = "googleAccessToken";
		const string _registrationComplete = "registrationComplete";
		const string _azureUserId = "azureUserId";
		const string _azureAuthToken = "azureAuthToken";
		const string _enablePushNotifications = "enablePushNotifications";

**Comment by rob-derosa** [comment]
All of those settings are set in code when the user is registering or logging into the app. You do not need to set those yourself.

**Comment by rob-derosa** [comment]
@itsaboutcode - to build the project, clone it and compile. There isn't much else to it other than that.
