### ISSUE TITLE
Error 403 - This web app is stopped.

### ISSUE THREAD

**Issue by AwsomeCode** [xamarin/Sport#21]
Web services is not alive.
https://xamarin-sportv2.azurewebsites.net/

**Comment by fbeenaerts** [comment]
Any news on this? URL is in the Keys.cs file and indeed not accessible

**Comment by rob-derosa** [comment]
The site is up and running for me - https://xamarin-sportv2.azurewebsites.net/

Are you still having issues connecting on your end?

![screen shot 2017-01-26 at 11 08 18 am](https://cloud.githubusercontent.com/assets/7773968/22344053/c77a1a16-e3b7-11e6-82dd-0b38cd518866.png)

**Comment by potvin23** [comment]
hey @rob-derosa, I'm also getting a 403 at the time of this reply.

![image](https://cloud.githubusercontent.com/assets/3825537/22380461/907d164c-e48b-11e6-81c7-139f66506058.png)

**Comment by rob-derosa** [comment]
My subscription limit has been reached - sorting it out now...

**Comment by potvin23** [comment]
@rob-derosa  thanks, I'll check back every once in a while

**Comment by rob-derosa** [comment]
Service will be back up tomorrow.

**Comment by AwsomeCode** [comment]
Is it up? 403 gone but I am getting diverted to Azure Login page.

**Comment by rob-derosa** [comment]
Should be back up now. Please let me know if you're unable to reach the server.

**Comment by potvin23** [comment]
Looking good, thanks
