### ISSUE TITLE
DB dump?

### ISSUE THREAD

**Issue by nbosco** [xamarin/Sport#26]
Would it be possible to get a DB dump?

**Comment by nbosco** [comment]
Im trying to use my own Azure App Service with the app, is there any instructions on how to get it setup?

**Comment by rob-derosa** [comment]
The DB is generated for you using Entity Framework code-first. There is no attached file or existing schema, the C# model classes are responsible for dictating the schema.

**Comment by nbosco** [comment]
I see, is there any specific way to set up Google Auth services with the app in the codebase I'm receiving this [error.](https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwipjJmQ5-XSAhVLw1QKHbqsAlwQjBwIBA&url=https%3A%2F%2Fus.v-cdn.net%2F5019960%2Fuploads%2FFileUpload%2Fa9%2Fc51ea9e8b4baf14680071103c62b19.png&psig=AFQjCNH4rM3uBOohIhWOM66soYwXv4Ps7g&ust=1490124135577879)

**Comment by rob-derosa** [comment]
You would need to sign up for your own Google Auth key or you could incorporate your own authentication paradigm.

**Comment by nbosco** [comment]
I've setup the Google Auth Key with the Azure Mobile app service. However, I still receive this error: https://gyazo.com/6317873a1d9cb8c9931de35a4ec958be

Is it because Google only uses its Android libraries to authenticate now, instead of  webview?

**Comment by nbosco** [comment]
Would it be possible to post the app.js file from your backend? It would be really helpful :)

**Comment by rob-derosa** [comment]
It's possible Google has changed their policy. You might try using Azure AD instead (the source code has sample of this too). I don't really have any control over how the Google Auth page is displayed since I'm using Azure Mobile Service SDK to achieve this.

There is no app.js file - the backend is C#/.NET, not node.

**Comment by nbosco** [comment]
Ah I see, but if they changed their policy then it wouldn't work with your backend as well (https://xamarin-sportv2.azurewebsites.net/), would it be possible to share the https://xamarin-sportv2.azurewebsites.net/ backend in the repo somehow, I think you might have some settings that I might be missing? Did you have to open the URL https://xamarin-sportv2.azurewebsites.net/.auth/login/google/callback in the Azure?

**Comment by rob-derosa** [comment]
It would depend on when you created your Google Auth ID - perhaps legacy IDs are given a bit more flexibility on shutdown time.

I've shared all the code that it takes to build the front and backend as part of this repro. There isn't any hidden code or settings.
