### ISSUE TITLE
Wanted, documentation on how the app was designed.

### ISSUE THREAD

**Issue by makerofthings7** [xamarin/Sport#28]
This is a beautiful app, that also is coded very well. 

I'm new to Xamarin forms, and seeing many approaches that weren't covered in Xamarin University.  

There is an interesting use of many technologies, and each one is worth looking at.

**Comment by rob-derosa** [comment]
This is a side project I develop on the side. There is no accompanying documentation or pattern approaches published. I'd be happy to answer any questions but this is very much a "Rob's approach" to developing mobile apps for Xamarin Forms.
