### ISSUE TITLE
Random bugs

### ISSUE THREAD

**Issue by shainefisher** [xamarin/Sport#29]
I love the code of this app, but there are a couple of bugs that need noting.

Azure AD does not resolve the profile email and if correctly, I needed to drill into _identity Claims and find the correct values, not big, but stops the app at the alias screen with an unhandled exception.

To post new Leagues from the app using InsertAsync you need to add Index to LeagueDto (service project) and edit the controller LeagueToDto method to use it.

There may be more as I work my way through, but someone might be having issues and this might help them.

**Comment by shainefisher** [comment]
Would have made more sense to tell you solution, rather then just the problem, lines 339-442 in the AuthenticationViewModel should read:

var ad = new ActiveDirectoryUserProfile();
ad.Id = _identity.UserClaims.SingleOrDefault(c => c.Typ == "http://schemas.microsoft.com/identity/claims/objectidentifier")?.Val;
ad.Email = _identity.UserId;
ad.Name = _identity.UserClaims.SingleOrDefault(c => c.Typ == "name")?.Val;

**Comment by rob-derosa** [comment]
I'm re-hauling the entire auth code since Azure Mobile but will consider this assuming it's still valid after refactoring. Thanks!

**Comment by shainefisher** [comment]
Not a problem, I'm slowly extending the app to make something new, because your code is really well organised I'm keeping the same pattern. Apart from little quirks like above it's great to work with. I use Facebook and Twitter auth so the Google change wasn't a show stopper for me.
