### ISSUE TITLE
When compile in window xamarin, getting a error on keyid line (Utility.cs)

### ISSUE THREAD

**Issue by rex232** [xamarin/Sport#3]
the error is unexpected character '$'

Anyone know why?

	static internal string GetSecured(string key, string clientId, string service, string sharedGroup)
		{
			var keyId = $"{clientId} - {key}";

**Comment by senzacionale** [comment]
Same problem here in WIndows environment

**Comment by Therzok** [comment]
You need VS 2015 or MSBuild Tools 14 to use C# 6 features on Windows.

**Comment by Therzok** [comment]
If you're using Xamarin Studio on Windows, I suggest you use the [Roslyn Preview Release](http://forums.xamarin.com/discussion/53121/preview-release-xamarin-studio-6-0-with-roslyn-support).

**Comment by senzacionale** [comment]
Thank you!
