### ISSUE TITLE
XAML previewing issue in MatchResultsFormPage

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Sport#31]
From [51134](https://bugzilla.xamarin.com/show_bug.cgi?id=51134), a PR was opened for one of the pages not working, but it appears that `MatchResultsFormPage` has some sort of NRE (starting around line 33, at least based on what the error says) that prevents the Forms previewer from working.

<img width="1422" alt="screen shot 2017-05-22 at 2 30 18 pm" src="https://cloud.githubusercontent.com/assets/1251024/26325109/42146cba-3efb-11e7-9614-4b6698dbf1d6.png">

**Comment by rob-derosa** [comment]
There are XAML previewer issues throughout the app. This is due to the bugs in the previewer and the fact that a lot of the source code needs to be refactored to consider non-state.

I would recommend Gorilla Player if you want to live edit against this app.
