### ISSUE TITLE
XS unable to build Sport due to '$' in Utility.cs

### ISSUE THREAD

**Issue by nSolvePR** [xamarin/Sport#6]
`C:\dev_xam\X\Sport-master\Sport.Android\Providers\Utility.cs(16,16): Error CS1056: Unexpected character '$' (CS1056) (Sport.Android)`

**Comment by rob-derosa** [comment]
Certain aspects take advantage of C# 6 features - this is one such case. Please ensure you're C# 6 compatible or revert the code to the previous string format.

**Comment by nSolvePR** [comment]
"Xamarin Studio for Windows does not currently support C# 6 features in the editor. This will be available in a future preview."  ah,  :-(
